CREATE PROCEDURE [dbo].[Insert_Bill]
	@Id INT OUTPUT,
	@TransactionNo VARCHAR(100),
	@CompanyId INT,
	@LocationId INT,
	@DiningTableId INT,
	@CustomerId INT = NULL,
	@TransactionDateTime DATETIME,
	@FinancialYearId INT,
	@TotalPeople INT,
	@TotalItems INT,
	@TotalQuantity MONEY,
	@BaseTotal MONEY,
	@ItemDiscountAmount MONEY,
	@TotalAfterItemDiscount MONEY,
	@TotalInclusiveTaxAmount MONEY,
	@TotalExtraTaxAmount MONEY,
	@TotalAfterTax MONEY,
	@DiscountPercent DECIMAL(5, 2),
	@DiscountAmount MONEY,
	@ServiceChargePercent DECIMAL(5, 2),
	@ServiceChargeAmount MONEY,
	@RoundOffAmount MONEY,
	@TotalAmount MONEY,
	@Cash MONEY,
	@Card MONEY,
	@UPI MONEY,
	@Credit MONEY,
	@Remarks VARCHAR(MAX),
	@CreatedBy INT,
	@CreatedAt DATETIME,
	@CreatedFromPlatform VARCHAR(MAX),
	@Running BIT,
	@Status BIT,
	@LastModifiedBy INT,
	@LastModifiedAt DATETIME,
	@LastModifiedFromPlatform VARCHAR(MAX)
AS
BEGIN
	IF @Id = 0
	BEGIN
		INSERT INTO [dbo].[Bill]
		(
			[TransactionNo],
			[CompanyId],
			[LocationId],
			[DiningTableId],
			[CustomerId],
			[TransactionDateTime],
			[FinancialYearId],
			[TotalPeople],
			[TotalItems],
			[TotalQuantity],
			[BaseTotal],
			[ItemDiscountAmount],
			[TotalAfterItemDiscount],
			[TotalInclusiveTaxAmount],
			[TotalExtraTaxAmount],
			[TotalAfterTax],
			[DiscountPercent],
			[DiscountAmount],
			[ServiceChargePercent],
			[ServiceChargeAmount],
			[RoundOffAmount],
			[TotalAmount],
			[Cash],
			[Card],
			[UPI],
			[Credit],
			[Remarks],
			[CreatedBy],
			[CreatedAt],
			[CreatedFromPlatform],
			[Running],
			[Status]
		)
		VALUES
		(
			@TransactionNo,
			@CompanyId,
			@LocationId,
			@DiningTableId,
			@CustomerId,
			@TransactionDateTime,
			@FinancialYearId,
			@TotalPeople,
			@TotalItems,
			@TotalQuantity,
			@BaseTotal,
			@ItemDiscountAmount,
			@TotalAfterItemDiscount,
			@TotalInclusiveTaxAmount,
			@TotalExtraTaxAmount,
			@TotalAfterTax,
			@DiscountPercent,
			@DiscountAmount,
			@ServiceChargePercent,
			@ServiceChargeAmount,
			@RoundOffAmount,
			@TotalAmount,
			@Cash,
			@Card,
			@UPI,
			@Credit,
			@Remarks,
			@CreatedBy,
			@CreatedAt,
			@CreatedFromPlatform,
			@Running,
			@Status
		)
		SET @Id = SCOPE_IDENTITY()
	END

	ELSE
	BEGIN
		UPDATE [dbo].[Bill]
		SET
			[TransactionNo] = @TransactionNo,
			[CompanyId] = @CompanyId,
			[LocationId] = @LocationId,
			[DiningTableId] = @DiningTableId,
			[CustomerId] = @CustomerId,
			[TransactionDateTime] = @TransactionDateTime,
			[FinancialYearId] = @FinancialYearId,
			[TotalPeople] = @TotalPeople,
			[TotalItems] = @TotalItems,
			[TotalQuantity] = @TotalQuantity,
			[BaseTotal] = @BaseTotal,
			[ItemDiscountAmount] = @ItemDiscountAmount,
			[TotalAfterItemDiscount] = @TotalAfterItemDiscount,
			[TotalInclusiveTaxAmount] = @TotalInclusiveTaxAmount,
			[TotalExtraTaxAmount] = @TotalExtraTaxAmount,
			[TotalAfterTax] = @TotalAfterTax,
			[DiscountPercent] = @DiscountPercent,
			[DiscountAmount] = @DiscountAmount,
			[ServiceChargePercent] = @ServiceChargePercent,
			[ServiceChargeAmount] = @ServiceChargeAmount,
			[RoundOffAmount] = @RoundOffAmount,
			[TotalAmount] = @TotalAmount,
			[Cash] = @Cash,
			[Card] = @Card,
			[UPI] = @UPI,
			[Credit] = @Credit,
			[Remarks] = @Remarks,
			[Running] = @Running,
			[Status] = @Status,
			[LastModifiedBy] = @LastModifiedBy,
			[LastModifiedAt] = @LastModifiedAt,
			[LastModifiedFromPlatform] = @LastModifiedFromPlatform
		WHERE [Id] = @Id
	END

	SELECT @Id AS Id
END
