CREATE TABLE [dbo].[Bill]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [TransactionNo] VARCHAR(100) NOT NULL UNIQUE,
	[CompanyId] INT NOT NULL,
	[LocationId] INT NOT NULL,
	[DiningTableId] INT NOT NULL,
    [CustomerId] INT NULL,
	[TransactionDateTime] DATETIME NOT NULL,
	[FinancialYearId] INT NOT NULL,
	[TotalPeople] INT NOT NULL DEFAULT 1,
	[TotalItems] INT NOT NULL DEFAULT 0,
	[TotalQuantity] MONEY NOT NULL DEFAULT 0,
	[BaseTotal] MONEY NOT NULL DEFAULT 0,
	[ItemDiscountAmount] MONEY NOT NULL DEFAULT 0,
	[TotalAfterItemDiscount] MONEY NOT NULL DEFAULT 0,
	[TotalInclusiveTaxAmount] MONEY NOT NULL DEFAULT 0,
	[TotalExtraTaxAmount] MONEY NOT NULL DEFAULT 0,
	[TotalAfterTax] MONEY NOT NULL DEFAULT 0,
	[DiscountPercent] DECIMAL(5, 2) NOT NULL DEFAULT 0,
	[DiscountAmount] MONEY NOT NULL DEFAULT 0,
	[ServiceChargePercent] DECIMAL(5, 2) NOT NULL DEFAULT 0,
	[ServiceChargeAmount] MONEY NOT NULL DEFAULT 0,
	[RoundOffAmount] MONEY NOT NULL DEFAULT 0,
	[TotalAmount] MONEY NOT NULL DEFAULT 0,
    [Cash] MONEY NOT NULL DEFAULT 0, 
    [Card] MONEY NOT NULL DEFAULT 0, 
    [UPI] MONEY NOT NULL DEFAULT 0, 
    [Credit] MONEY NOT NULL DEFAULT 0,
	[Remarks] VARCHAR(MAX) NULL,
	[CreatedBy] INT NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT (((getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'India Standard Time')),
	[CreatedFromPlatform] VARCHAR(MAX) NOT NULL,
	[Running] BIT NOT NULL DEFAULT 1,
	[Status] BIT NOT NULL DEFAULT 1,
	[LastModifiedBy] INT NULL,
	[LastModifiedAt] DATETIME NULL, 
	[LastModifiedFromPlatform] VARCHAR(MAX) NULL,
    CONSTRAINT [FK_Bill_ToCompany] FOREIGN KEY ([CompanyId]) REFERENCES [Company]([Id]),
	CONSTRAINT [FK_Bill_ToLocation] FOREIGN KEY (LocationId) REFERENCES [Location](Id),
    CONSTRAINT [FK_Bill_ToDiningTable] FOREIGN KEY ([DiningTableId]) REFERENCES [DiningTable]([Id]),
    CONSTRAINT [FK_Bill_ToCustomer] FOREIGN KEY (CustomerId) REFERENCES [Customer](Id), 
    CONSTRAINT [FK_Bill_ToFinancialYear] FOREIGN KEY ([FinancialYearId]) REFERENCES [dbo].[FinancialYear]([Id]),
    CONSTRAINT [FK_Bill_ToUser] FOREIGN KEY ([CreatedBy]) REFERENCES [User]([Id]),
	CONSTRAINT [FK_Bill_LastModifiedBy_ToUser] FOREIGN KEY ([LastModifiedBy]) REFERENCES [User]([Id])
)
